
project_id = "uicsbcxkvqzfhacdpjtz"

[functions.generate-ai-reply]
verify_jwt = false

[functions.post-tweet-reply]
verify_jwt = false

[functions.twitter-oauth]
verify_jwt = false

[functions.twitter-oauth-callback]
verify_jwt = false
