// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uicsbcxkvqzfhacdpjtz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVpY3NiY3hrdnF6ZmhhY2RwanR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyNzM0OTAsImV4cCI6MjA2NDg0OTQ5MH0.tg7DLUhFWwpxZI71Ga2LKQ-PSYUCdXB2kKZ582Msj2s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);